### ISSUE TITLE
Blazor.Animate is now part of Blazorise

### ISSUE THREAD

**Issue by stsrki** [mikoskinen/Blazor.Animate#18]
Hi @mikoskinen, I found your library while searching for a good Blazor animation component and I found it really good.

I'm a creator of [Blazorise](https://github.com/stsrki/Blazorise) component library and I think your work would really fit into Blazorise. What I propose is for you to become a collaborator on Blazorise and then make `Blazor.Animate` a part of Blazorise extensions. That way you would be part of a larger community and your work can reach more people.

I would really like you to consider it. Please let me know what you think.

**Comment by Eastiling** [comment]
I use Blazorise as part of my work and its really good. So if this could bake in, especially if exit animations could be supported, that would be amazing.

**Comment by mikoskinen** [comment]
Hi @stsrki and thanks for the message. Sounds good and what you propose gets a yes from my side.

Just let me know the next steps through this issue or through email :)

**Comment by stsrki** [comment]
That's good to hear :)

To start, I would first describe the Blazorise so you have a bigger picture in mind. It is basically a component library with abstraction over multiple different CSS libraries. What it means is by itself Blazorise is doing nothing. It has to have a _provider_ implementation to make it work(Bootstrap, Bulma, AntDesign, etc.).

My idea with `Blazor.Animate` was to create it as an extension(`Blazorise.Animate`), just like we already have Blazorise.DataGrid or Blazorise.TreeView to name a few.

We can definitely talk more over email, a gitter, or some other communication channel over the details.

**Comment by stsrki** [comment]
I would like to say that complete **Blazor.Animate** code is transferred to [Blazorise](https://github.com/stsrki/Blazorise) and it's already available as a preview NuGet package.

**Comment by mikoskinen** [comment]
Excellent, thanks again for all the work! I'll close this issue and update the readme to direct new users to Blazorise.

**Comment by BRGustavoRibeiro** [comment]
@mikoskinen @stsrki 

Blazor.Animate previously operated under the MIT License. Blazorise, as we know, uses a custom non-commercial license. I'm currently developing an application for local government, so this situation affects me.

Can I still use Blazorise.Animate under the MIT license, or has the project been fully incorporated into Blazorise's licensing terms?

**Comment by stsrki** [comment]
> [@mikoskinen](https://github.com/mikoskinen) [@stsrki](https://github.com/stsrki)
> 
> Blazor.Animate previously operated under the MIT License. Blazorise, as we know, uses a custom non-commercial license. I'm currently developing an application for local government, so this situation affects me.
> 
> Can I still use Blazorise.Animate under the MIT license, or has the project been fully incorporated into Blazorise's licensing terms?

Blazor.Animate can be used under MIT license only up to 0.9.4 version. If I remember it correctly. After that version it was made dual license.
