### ISSUE TITLE
Blazor Webassembly sample?

### ISSUE THREAD

**Issue by RichardBr** [mikoskinen/Blazor.Animate#2]
Can you please provide a sample that would work on Blazor Web assembly.

**Comment by mgernand** [comment]
Hi @RichardBr,

just add the following in you `index.html` below the `blazor.webassembly.js` script and it works.

```html
<script src="_content/BlazorAnimate/blazorAnimateInterop.js"></script>
```
@mikoskinen I suggest you include the `blazorAnimateInterop.js` file as embedded resource. I use project configuration like below for this. 

```xml
  <ItemGroup>
    <!-- .js/.css files will be referenced via <script>/<link> tags; other content files will just be included in the app's 'dist' directory without any tags referencing them -->
    <EmbeddedResource Include="content\**\*.js" LogicalName="blazor:js:%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="content\**\*.css" LogicalName="blazor:css:%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="content\**" Exclude="**\*.ts;**\*.js;**\*.css" LogicalName="blazor:file:%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
```

**Comment by mikoskinen** [comment]
Thank you @mgernand for the tip. There's now a new 2.0.0 release available which targets .NET Core 3.1. I used the the method mentioned here https://github.com/aspnet/AspNetCore/issues/13103#issuecomment-555172130 to make sure that things should now work better with the Webassembly version of Blazor.

@RichardBr there's now a new WebAssembly-based sample in the repository.
